{% set name = "aicssegmentation" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aicssegmentation-{{ version }}.tar.gz
  sha256: ed01b749bb45c7a579db4108744d5264d4a9d26043601797e4ace1fc076a6185

build:
  entry_points:
    - batch_processing=aicssegmentation.bin.batch_processing:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner >=5.2
    - python >=3.7
  run:
    - aicsimageio >=4.0.5
    - dask-core
    - itk
    - itkwidgets
    - jupyter
    - matplotlib-base
    - napari
    - numpy >=1.15.1
    - pandas >=0.23.4
    - python >=3.7
    - scikit-image >=0.18.0,<0.19.0
    - scipy >=1.1.0

test:
  imports:
    - aicssegmentation
  commands:
    - pip list
    # - pip check
    - batch_processing --help
  requires:
    - pip

about:
  home: https://github.com/AllenCell/aicssegmentation
  summary: Part 1 of Allen Cell and Structure Segmenter
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jxchen01
